package com.pos.backend.constant.enums;

public enum ApprovalRequestType {
    CANCEL_INVOICE,
    REFUND_RETURN,
    DISCOUNT_EXCEEDS_THRESHOLD,
    COMPLIMENTARY,
    REOPEN_PAID_INVOICE,
    CANCEL_ITEM_AFTER_KITCHEN,
    CANCEL_KITCHEN_TICKET,
    PRICE_CHANGE,
    PERMISSION_CHANGE,
    USER_CREATE_DELETE,
    DELETE_IMPORTANT_DATA,
    CREATE_TABLE_FLOOR,
}
