const routes = {
    login: '/login',
    register: '/register',
    otp: '/otp',
    resetPassword: '/reset-password',
    forgotPassword: '/forgot-password',
    emailVerify: '/email-verification',
    dashboard: '/dashboard',
    pos: '/pos',
    orders: '/orders',
    kitchen: '/kitchen',
    reservation: '/reservation',
    categories: '/categories',
    items: '/items',
    addons: '/addons',
    coupons: '/coupons',
    tables: '/tables',
    customers: '/customers',
    invoices: '/invoices',
    payments: '/payments',
    users: '/users',
    'role-permissions': '/role-permissions',
    'earning-reports': '/reports/earning-report',
    'order-reports': '/reports/order-report',
    'sale-reports': '/reports/sale-report',
    'customer-reports': '/reports/customer-report',
    'audit-reports': '/reports/audit-report',
    'store-settings': '/store-settings',
    'tax-settings': '/tax-settings',
    'print-settings': '/print-settings',
    'payment-settings': '/payment-settings',
    'delivery-settings': '/delivery-settings',
    'notifications-settings': '/notifications-settings',
    'integrations-settings': '/integrations-settings',
};

export default routes;
