server:
  port: ${PORT:8080}
  servlet:
    context-path: /restaurant-pos

spring:
  profiles:
    default: local

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    clean-disabled: true

logging:
  level:
    org.flywaydb: INFO
    org.hibernate.SQL: INFO

jwt:
  access-token-expiration: 30
  refresh-token-expiration: 10080
