server:
  port: 8080
  servlet:
    context-path: /restaurant-pos

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/restaurant_pos_db
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
